name: EDML CI/CD Runner Workflow Generation

on:
  push:
    branches:
      - 'master'

jobs:
  main:
    name: cicd-runner-creation
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Edml CI/CD
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Docker Login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Maven settings configuration
        run: envsubst < .github/settings.template.xml > settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image creation
        run: ./mvnw assembly:single package dockerfile:push -s settings.xml